/*
 * SPDX-FileCopyrightText: 1997 - 2023 Berkeley Lab; 2023 - 2025 Yadong Zeng<zdsjtu@gmail.com>
 *
 * SPDX-License-Identifier: LicenseRef-OpenSource
 * Modified from IAMR, originally developed at Lawrence Berkeley National Lab.
 * Original source: https://github.com/AMReX-Fluids/IAMR
 */

#ifndef IAMR_RegType_H_
#define IAMR_RegType_H_

enum RegType { interior, exterior, periodic, refWall, inflow,
                outflow, REG_TYPE_SIZE};

#endif
